In [4]:
import numpy as np 

arr = np.arange(1, 21)
print("Array:")
print(arr)

print("\nShape of the array:", arr.shape)
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

matrix = arr.reshape(4, 5)
print("\n4 × 5 Matrix:")
print(matrix)
print(matrix[1])
print("\nThird Column:")
print(matrix[:, 2])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Shape of the array: (20,)
Maximum value: 20
Minimum value: 1
Mean: 10.5
Standard Deviation: 5.766281297335398

4 × 5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]

Third Column:
[ 3  8 13 18]


In [5]:
import numpy as np 
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print("Addition:", np.add(A, B))
print("Subtraction:", np.subtract(A, B))
print("Element-wise Multiplication:", np.multiply(A, B))
print("Element-wise Division:",np.divide(A, B))
print("Sum of all Elements in A:",np.sum(A))

Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Element-wise Multiplication: [  50  200  450  800 1250]
Element-wise Division: [2. 2. 2. 2. 2.]
Sum of all Elements in A: 150


In [6]:
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["ravi", "priya", "kiran", "anu", "sita"],
    "Marks": [85, 92, 78, 88, 95]
}
df = pd.DataFrame(data)

print("DataFrame:")
print(df)
print("\nFirst Three Records:")
print(df.head(3))
print("\nAverage Marks:", df["Marks"].mean())
print("\nStudent with Highest Marks:", df.loc[df["Marks"].idxmax()])
print("\nStudent with Lowest Marks:", df.loc[df["Marks"].idxmin()])

def grade(mark):
    if mark >= 90:
        return 'A'
    elif mark >= 80:
        return 'B'
    else:
        return 'C'

df["Grade"] = df["Marks"].apply(grade)

print("\nDataFrame with Grades:")
print(df)

DataFrame:
   Roll No   Name  Marks
0      101   ravi     85
1      102  priya     92
2      103  kiran     78
3      104    anu     88
4      105   sita     95

First Three Records:
   Roll No   Name  Marks
0      101   ravi     85
1      102  priya     92
2      103  kiran     78

Average Marks: 87.6

Student with Highest Marks: Roll No     105
Name       sita
Marks        95
Name: 4, dtype: object

Student with Lowest Marks: Roll No      103
Name       kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grades:
   Roll No   Name  Marks Grade
0      101   ravi     85     B
1      102  priya     92     A
2      103  kiran     78     C
3      104    anu     88     B
4      105   sita     95     A


In [7]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
}
df = pd.DataFrame(data)
df["Total Value"] = df["Price"] * df["Quantity"]
print("DataFrame with Total Value:")
print(df)

highest = df.loc[df["Total Value"].idxmax()]
print("\nProduct with Highest Total Value:")
print(highest)

overall_value = df["Total Value"].sum()
print("\nOverall Inventory Value:", overall_value)

DataFrame with Total Value:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Product with Highest Total Value:
Product        Laptop
Price           50000
Quantity           10
Total Value    500000
Name: 0, dtype: object

Overall Inventory Value: 711000


In [4]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target

print("First Five Records:")
print(df.head())
print("\nNumber of Rows and Columns:")
print(df.shape)
print("\nColumn Names:")
print(df.columns.tolist())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nSummary Statistics:")
print(df.describe())
print("\nNumber of Samples in Each Class:")
print(df['species'].value_counts())

First Five Records:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  

Number of Rows and Columns:
(150, 5)

Column Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

Missing Values:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

Summary Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000       